services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastforge-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
    - DOCKER_ENV=1
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    networks:
      - fastforge-network
  adminer:
    image: adminer:5.3.0
    restart: on-failure:5
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha
    mem_limit: 128m
    cpu_shares: 256
    depends_on:
      - db
    networks:
      - fastforge-network
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - fastforge-network
volumes:
  postgres_data:
networks:
  fastforge-network:
    driver: bridge
